ALDIWAN_ROOT = 'https://www.aldiwan.net'


ERAS = [
    ['الجاهلي', 'https://www.aldiwan.net/cat-poets-pre-islamic-period'],
    ['المخضرمون', 'https://www.aldiwan.net/cat-poets-veteran'],
    ['صدر الإسلام', 'https://www.aldiwan.net/cat-poets-Islamic-era'],
    ['الأموي', 'https://www.aldiwan.net/cat-poets-umayyad-era'],
    ['العباسي', 'https://www.aldiwan.net/cat-poets-abbasid-era'],
    ['الأيوبي', 'https://www.aldiwan.net/cat-poets-ayubi-era'],
    ['المملوكي', 'https://www.aldiwan.net/cat-poets-mamluk-era'],
    ['الأندلسي', 'https://www.aldiwan.net/cat-poets-andalusian-era'],
    ['العثماني', 'https://www.aldiwan.net/cat-poets-ottoman-era'],
    ['الحديث - الإمارات', 'https://www.aldiwan.net/cat-poets-uae'],
    ['الحديث - البحرين', 'https://www.aldiwan.net/cat-poets-bahrain'],
    ['الحديث - الجزائر', 'https://www.aldiwan.net/cat-poets-algeria'],
    ['الحديث - السعودية', 'https://www.aldiwan.net/cat-poets-saudi-arabia'],
    ['الحديث - السودان', 'https://www.aldiwan.net/cat-poets-sudan'],
    ['الحديث - العراق', 'https://www.aldiwan.net/cat-poets-iraq'],
    ['الحديث - المغرب', 'https://www.aldiwan.net/cat-poets-morocco'],
    ['الحديث - اليمن', 'https://www.aldiwan.net/cat-poets-yemen'],
    ['الحديث - تونس', 'https://www.aldiwan.net/cat-poets-tunisia'],
    ['الحديث - سوريا', 'https://www.aldiwan.net/cat-poets-syria'],
    ['الحديث - عمان', 'https://www.aldiwan.net/cat-poets-oman'],
    ['الحديث - فلسطين', 'https://www.aldiwan.net/cat-poets-palestine'],
    ['الحديث - لبنان', 'https://www.aldiwan.net/cat-poets-lebanon'],
    ['الحديث - ليبيا', 'https://www.aldiwan.net/cat-poets-libya'],
    ['الحديث - مصر', 'https://www.aldiwan.net/cat-poets-egypt'],
    ['الحديث - الأردن', 'https://www.aldiwan.net/cat-poets-jordan'],
    ['الحديث - الكويت', 'https://www.aldiwan.net/cat-poets-kuwait'],
    ['الحديث - قطر', 'https://www.aldiwan.net/cat-poets-qatar'],
    ['الحديث - موريتانيا', 'https://www.aldiwan.net/cat-poets-mauritania'],
    ['الحديث - الصومال', 'https://www.aldiwan.net/cat-poets-Soomaaliya'],
    ['الحديث - السنغال', 'https://www.aldiwan.net/cat-poets-Senegal'],
]
