ALDIWAN_ROOT = 'https://www.aldiwan.net'


ERAS = [
    ['الجاهلي', 'https://www.aldiwan.net/cat-poets-pre-islamic-period'],
    ['المخضرمون', 'https://www.aldiwan.net/cat-poets-veteran'],
    ['صدر الإسلام', 'https://www.aldiwan.net/cat-poets-Islamic-era'],
    ['الأموي', 'https://www.aldiwan.net/cat-poets-umayyad-era'],
    ['العباسي', 'https://www.aldiwan.net/cat-poets-abbasid-era'],
    ['الأيوبي', 'https://www.aldiwan.net/cat-poets-ayubi-era'],
    ['المملوكي', 'https://www.aldiwan.net/cat-poets-mamluk-era'],
    ['الأندلسي', 'https://www.aldiwan.net/cat-poets-andalusian-era'],
    ['العثماني', 'https://www.aldiwan.net/cat-poets-ottoman-era'],
    ['الحديث - الإمارات', 'https://www.aldiwan.net/cat-poets-uae'],
    ['الحديث - البحرين', 'https://www.aldiwan.net/cat-poets-bahrain'],
    ['الحديث - الجزائر', 'https://www.aldiwan.net/cat-poets-algeria'],
    ['الحديث - السعودية', 'https://www.aldiwan.net/cat-poets-saudi-arabia'],
    ['الحديث - السودان', 'https://www.aldiwan.net/cat-poets-sudan'],
    ['الحديث - العراق', 'https://www.aldiwan.net/cat-poets-iraq'],
    ['الحديث - المغرب', 'https://www.aldiwan.net/cat-poets-morocco'],
    ['الحديث - اليمن', 'https://www.aldiwan.net/cat-poets-yemen'],
    ['الحديث - تونس', 'https://www.aldiwan.net/cat-poets-tunisia'],
    ['الحديث - سوريا', 'https://www.aldiwan.net/cat-poets-syria'],
    ['الحديث - عمان', 'https://www.aldiwan.net/cat-poets-oman'],
    ['الحديث - فلسطين', 'https://www.aldiwan.net/cat-poets-palestine'],
    ['الحديث - لبنان', 'https://www.aldiwan.net/cat-poets-lebanon'],
    ['الحديث - ليبيا', 'https://www.aldiwan.net/cat-poets-libya'],
    ['الحديث - مصر', 'https://www.aldiwan.net/cat-poets-egypt'],
    ['الحديث - الأردن', 'https://www.aldiwan.net/cat-poets-jordan'],
    ['الحديث - الكويت', 'https://www.aldiwan.net/cat-poets-kuwait'],
    ['الحديث - قطر', 'https://www.aldiwan.net/cat-poets-qatar'],
    ['الحديث - موريتانيا', 'https://www.aldiwan.net/cat-poets-mauritania'],
    ['الحديث - الصومال', 'https://www.aldiwan.net/cat-poets-Soomaaliya'],
    ['الحديث - السنغال', 'https://www.aldiwan.net/cat-poets-Senegal'],
]


RHYME_MAPPING = [
    (['النون (ن)', '(النون)'], 'ن'),
    (['الميم (م)', '(الميم)'], 'م'),
    (['اللام (ل)', '(اللام)'], 'ل'),
    (['الراء (ر)', '(الراء)'], 'ر'),
    (['القاف (ق)', '(القاف)'], 'ق'),
    (['الفاء (ف)', '(الفاء)'], 'ف'),
    (['العين (ع)', '(العين)'], 'ع'),
    (['السين (س)'], 'س'),
    (['الباء (ب)'], 'ب'),
    (['الياء (ي)', '(الياء)'], 'ي'),
    (['الياء (ى)'], 'ى'),
    (['الدال (د)', '(الدال)'], 'د'),
    (['الصاد (ص)'], 'ص'),
    (['ألف الهمزة (أ)'], 'أ'),
    (['التاء (ت)'], 'ت'),
    (['التاء المربوطة (ة)'], 'ة'),
    (['الضاد (ض)'], 'ض'),
    (['الحاء (ح)', '(الحاء)'], 'ح'),
    (['الألف (ا)', '(الالف)'], 'ا'),
    (['الألف (إ)'], 'إ'),
    (['الكاف (ك)'], 'ك'),
    (['الشين (ش)'], 'ش'),
    (['الجيم (ج)'], 'ج'),
    (['الهمزة (ء)'], 'ء'),
    (['الزاى (ز)'], 'ز'),
    (['الواو (و)'], 'و'),
    (['الطاء (ط)'], 'ط'),
    (['ياء همزة (ئ)'], 'ئ'),
    (['الثاء (ث)'], 'ث'),
    (['الخاء (خ)'], 'خ'),
    (['(لام مكسورة)'], 'لِ'),
    (['الذال (ذ)'], 'ذ'),
    (['الهاء (ه)'], 'ه'),
    (['الغين (غ)'], 'غ'),
    (['واو همزة (ؤ)'], 'ؤ'),
    (['الظاء (ظ)'], 'ظ'),
    (['(لا)'], 'لا'),
]
